### ISSUE TITLE
Bad Request

### ISSUE THREAD

**Issue by cirrusflyer** [alfiosalanitri/hetzner-server-manager#2]
Running using Docker Compose, but seeing this when attempting to add a new project:

Bad Request
The CSRF session token is missing.

**Comment by alfiosalanitri** [comment]
Are you using my image, or did you clone the repo and build the image yourself?

**Comment by cirrusflyer** [comment]
Image, thanks.

**Comment by alfiosalanitri** [comment]
Could you give me more details? 
-  Operating system
-  Are you using a reverse proxy?
-  Have you configured the .env file?
-  Could you describe the steps you followed?

**Comment by alimahjoub** [comment]
Operating system: Ubuntu 24.04.4 LTS
Hi, I also encountered the same error. 
I ran Docker Compose and edited .env. I created the keys with Python. 
I logged into the panel with the IP address. 
There is no cloudflare or reverse proxy behind it.

**Comment by alfiosalanitri** [comment]
> Hi, I also encountered the same error. 
> I ran Docker Compose and edited .env. I created the keys with Python. 
> I logged into the panel with the IP address. 
> There is no cloudflare or reverse proxy behind it.

Hi both,

I found the root cause: the app hardcodes SESSION_COOKIE_SECURE = True, so when you access it over plain HTTP (e.g. http://your-server-ip:5000, no reverse proxy/TLS in front), the browser refuses to store/send the session cookie. Since Flask-WTF keeps the CSRF token in that session cookie, it ends up missing on form submit — that's exactly the "Bad Request: The CSRF session token is missing" error.

I just pushed a fix that makes this configurable via a new SESSION_COOKIE_SECURE environment variable (defaults to true, so nothing changes if you're already using HTTPS/a reverse proxy).

To fix it on your setup:
- Pull the latest image once it's published 
- Add this line to your .env file:
`SESSION_COOKIE_SECURE=false`
- Restart the container (docker compose up -d --force-recreate or similar).

Could you give it a try and confirm it resolves the issue on your end?

Note: this disables the "secure" flag on the session cookie, meaning it's sent unencrypted over HTTP. If possible, I'd still recommend putting the app behind HTTPS (reverse proxy, Cloudflare Tunnel, etc.) rather than exposing it raw over HTTP.

**Comment by alimahjoub** [comment]
I pulled the latest changes, recreated the container, and set SESSION_COOKIE_SECURE=false in my .env file, but I'm still getting the same CSRF error.

<img width="2572" height="1352" alt="Image" src="https://github.com/user-attachments/assets/7622b9eb-171e-44b8-b3bf-d9a1fb31d22f" />

**Comment by alfiosalanitri** [comment]
You used the command `docker compose down && docker compose up -d` or `docker compose restart`?

**Comment by alfiosalanitri** [comment]
I just tested it locally and I don't have the reported problem.

<img width="2543" height="1438" alt="Image" src="https://github.com/user-attachments/assets/edeb74bd-d1b6-453a-a408-900d9cfee20b" />
